
title: Myrick Wang
email: myrickwan9@gmail.com
description: "Electrical & Electronic Engineering / University of Bristol. Research in Signal Processing and Embedded Systems."
baseurl: "" 
url: "https://rickkwang.github.io"
github_username: rickkwang
linkedin_username: myrick-wang
twitter_username: rickMygod

# Build settings
theme: null # Custom minimalist theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom Data
author:
  name: Myrick Wang
  avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Myrick&backgroundColor=d1d4f9"
  location: "Bristol, UK / Xiamen, China"
  school: "University of Bristol"
